**Numpy** - Numerical Python

Advantages of Numpy arrays:
1. Allows several mathematical operations
2. faster operations

In [2]:
#importing numpy library
import numpy as np

# **Numpy Arrays**

**Numpy array vs list**

In [3]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [4]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray



---

**Creating Arrays**

In [8]:
# creating a 1 dim array from Python lists or tuples:
a = np.array([1,2,3,4])
print(a)

b = np.array([[1, 2, 3,4,5], [4, 5, 6,7,8]])  # 2D array

#Creating arrays filled with zeros or ones:
zeros = np.zeros(5)  # Creates an array of 5 zeros
ones = np.ones((2, 3))  # Creates a 2x3 array of ones
z = np.full((5,4),5) # array of a particular value
I = np.eye(5) #identity matrix
Random = np.random.random((3,4)) #array with random values
range_array = np.random.randint(10,100,(3,5)) #random integer values array within a specific range
evenspace_value = np.linspace(10,30,5) #array of evenly spaced values --> specifying the number of values required
evenspace_step = np.arange(10,30,5) # array of evenly spaced values --> specifying the step

#Creating sequences of numbers:
sequence = np.arange(1, 11)  # Creates an array from 1 to 10


[1 2 3 4]


In [9]:
print(b.shape)  #dimension

print(b.dtype)#Datatype

print(b.ndim)   #No. of dimensions

print(b.size)   #No. of elements


(2, 5)
int64
2
10


In [10]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [30]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

**Array operations**

In [21]:
arr1=np.array([(1,2,3,4),(5,6,7,8)])
arr2=np.array([(10,20,50,60),(50,60,10,70)])

result_add = arr1 + arr2  # Addition
result_mul = arr1 * 2  # Scalar multiplication

print(result_add)

print(result_mul)


[[11 22 53 64]
 [55 66 17 78]]
[[ 2  4  6  8]
 [10 12 14 16]]


In [22]:
print(sum(arr1))
print(arr1.mean())
print(arr1.max())
print(arr1.min())

[ 6  8 10 12]
4.5
8
1


**Array Slicing and Indexing**

In [23]:
arr1[1:2]

array([[5, 6, 7, 8]])

In [29]:
#Array reshaping
arr3=np.array([1,2,3,4,5,6])
re_array=arr3.reshape(2,3)

#Array concatenation
concatenated = np.concatenate((arr1, arr2), axis=0)


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [32]:
print(a)
print(b)

[[1 5 8]
 [7 2 5]
 [5 5 9]]
[[12 19 10]
 [18 13 17]
 [13 16 17]]


In [33]:

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[13 24 18]
 [25 15 22]
 [18 21 26]]
[[-11 -14  -2]
 [-11 -11 -12]
 [ -8 -11  -8]]
[[ 12  95  80]
 [126  26  85]
 [ 65  80 153]]
[[0.08333333 0.26315789 0.8       ]
 [0.38888889 0.15384615 0.29411765]
 [0.38461538 0.3125     0.52941176]]


In [34]:

a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [35]:
print(a)
print(b)


[[5 5 2]
 [6 8 3]
 [0 6 3]]
[[14 11 18]
 [11 12 18]
 [19 11 12]]


In [36]:

print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 16 20]
 [17 20 21]
 [19 17 15]]
[[ -9  -6 -16]
 [ -5  -4 -15]
 [-19  -5  -9]]
[[70 55 36]
 [66 96 54]
 [ 0 66 36]]
[[0.35714286 0.45454545 0.11111111]
 [0.54545455 0.66666667 0.16666667]
 [0.         0.54545455 0.25      ]]


In [37]:

array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[3 6 4]
 [0 3 3]]
(2, 3)


In [38]:

# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)


[[3 0]
 [6 3]
 [4 3]]
(3, 2)


In [39]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 2 4]
 [0 7 9]]
(2, 3)


In [40]:

trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 0]
 [2 7]
 [4 9]]
(3, 2)


In [41]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 6 9]
 [7 5 4]]
(2, 3)


In [42]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 6]
 [9 7]
 [5 4]]
(3, 2)
